GET http://localhost:3000/api/auth
### GET the current session

POST http://localhost:3000/api/auth/register
content-type : application/json

{
  "username": "test",
  "password": "password"
}
### Creates a new user

POST http://localhost:3000/api/auth/login
content-type : application/json

{
  "username": "test",
  "password": "password"
}
### Attempts to login

POST http://localhost:3000/api/auth/logout
### Attempts to logout of current user

### GET the current session

POST http://localhost:3000/api/auth/admin/register
content-type : application/json

{
  "username": "test",
  "password": "password"
}

### Creates a new admin

POST http://localhost:3000/api/auth/admin/login
content-type : application/json

{
  "username": "test",
  "password": "password"
}

### Logs in an admin