
GET http://localhost:3000/api/tables/5af3576b-27f1-49fc-a993-6b92dbccaf88/rows
### getAll From ElephantSeals

GET http://localhost:3000/api/tables/7e637ce9-68cb-4dec-a7b1-81bb5fe13b6e/rows/raa1d2181831f98
### getOne From ElephantSeals
GET http://localhost:3000/api/tables/5a200d36-6cf3-4777-a9bc-2e588358f64b/rows/72b37c1d-a29a-4b7e-848f-6e53b50b37c8
### getOne From puffins with creator rule

POST http://localhost:3000/api/tables/5af3576b-27f1-49fc-a993-6b92dbccaf88/rows
content-type: application/json

{
  "size": "Extra big", "job" : "Accountant"
}
###

POST http://localhost:3000/api/tables/7e637ce9-68cb-4dec-a7b1-81bb5fe13b6e/rows
content-type: application/json

{
  "size": "Medium", "gender" : "unknown"
}
###

PATCH http://localhost:3000/api/tables/fbe7f769-ceed-4dd7-a2fe-c27df65a2c57/rows/27266678-f248-42d3-9d8a-c451fc80e543
content-type: application/json

{
  "Bigness": "Medium", "hometown" : "Dallas"
}
###
DELETE http://localhost:3000/api/tables/7e637ce9-68cb-4dec-a7b1-81bb5fe13b6e/rows/acc8e899-49f5-46a0-a6ce-e825cc3174aa
### deleteOne From todos

GET http://localhost:3000/custom
### Testing Custom Route