
GET http://localhost:3000/api/tables/52b22193-a0f1-4346-8f17-ccb0c2b4f7d5/rows
### getAll From ElephantSeals

GET http://localhost:3000/api/tables/7e637ce9-68cb-4dec-a7b1-81bb5fe13b6e/rows/raa1d2181831f98
### getOne From ElephantSeals
GET http://localhost:3000/api/tables/5a200d36-6cf3-4777-a9bc-2e588358f64b/rows/72b37c1d-a29a-4b7e-848f-6e53b50b37c8
### getOne From puffins with creator rule

POST http://localhost:3000/api/tables/2e6ad9a5b97161/rows
content-type: application/json

{
  "name": "Jimmy",
  "bear friend": "7e9bdc0b5f6f99"
}
###

POST http://localhost:3000/api/tables/7e637ce9-68cb-4dec-a7b1-81bb5fe13b6e/rows
content-type: application/json

{
  "size": "Medium", "gender" : "unknown"
}
###

PATCH http://localhost:3000/api/tables/9c589bca-a2b7-41ea-89b7-73e01c002f1d/rows/5f71b5d7-c5bd-4aa4-8b00-2243ca0c49b2
content-type: application/json

{
  "type": "Elephant Seal"
}
###
DELETE http://localhost:3000/api/tables/7e637ce9-68cb-4dec-a7b1-81bb5fe13b6e/rows/acc8e899-49f5-46a0-a6ce-e825cc3174aa
### deleteOne From todos

GET http://localhost:3000/custom
### Testing Custom Route