DELETE http://localhost:3000/api/schema/ElephantSeals
### Drops a table


POST http://localhost:3000/api/schema
content-type : application/json

{
  "name" : "ElephantSeals",
  "columns" : [{"name":"size","type":"text"},{"name":"sex","type":"text"}]
}
### Adds a table

POST http://localhost:3000/api/schema
content-type : application/json

{
  "name" : "Penguins",
  "columns" : [{"name":"species","type":"text"},{"name":"age","type":"text"}]
}

### Adds a table
PUT http://localhost:3000/api/schema
content-type : application/json

{
  "id": "2",
  "name" : "Penguins",
  "columns" : [{"name":"bigness","type":"text"}]
}
### Update Column

PUT http://localhost:3000/api/schema/b14f8abd-fc0e-4eb0-97bd-c57e65690c00
content-type : application/json

{
  "id": "b14f8abd-fc0e-4eb0-97bd-c57e65690c00",
  "name" : "BigSeals",
  "columns" : [{"id":"fd3fb92d-0e9b-4f55-8633-42a74d0ee228", "name":"size","type":"text"}, {"id":"6840d4bc-10b8-4d37-9847-321dd7fac071","name":"gender","type":"text"}]
}
### Rename Table

PUT http://localhost:3000/api/schema/b14f8abd-fc0e-4eb0-97bd-c57e65690c00
content-type : application/json

{
  "id": "b14f8abd-fc0e-4eb0-97bd-c57e65690c00",
  "name" : "ElephantSeals",
  "columns" : [{"id":"fd3fb92d-0e9b-4f55-8633-42a74d0ee228", "name":"size","type":"text"}]
}
### Drop a column

PUT http://localhost:3000/api/schema/f8ef4e7f-6596-4d2f-a488-9a3c092f58cb
content-type : application/json

{
  "id": "f8ef4e7f-6596-4d2f-a488-9a3c092f58cb",
  "name" : "ElephantSeals",
  "columns" : [{"id":"b64ab088-911b-4461-836b-4747aedf5988", "name":"size","type":"text"}, {"name":"gender","type":"text"}]
}
### Add a column


PUT http://localhost:3000/api/schema/b6d31866-5668-4a92-82e3-a4dc0df24df9
content-type : application/json

{
  "id": "b6d31866-5668-4a92-82e3-a4dc0df24df9",
  "name" : "ElephantSeals",
  "columns" : [{"id":"cd5b4013-e0d3-4274-a452-ccd621c76bc9", "name":"size","type":"number"}, {"id":"720f534b-423d-4982-a894-8be36d53dce9","name":"sex","type":"text"}]
}
### Rename a column


PUT http://localhost:3000/api/schema/b14f8abd-fc0e-4eb0-97bd-c57e65690c00
content-type : application/json

{
  "id": "b14f8abd-fc0e-4eb0-97bd-c57e65690c00",
  "name" : "ArcticSeals",
  "columns" : [{"id":"fd3fb92d-0e9b-4f55-8633-42a74d0ee228", "name":"Bigness","type":"text"}, {"name":"favFood","type":"text"}]
}
### Rename table, rename column, add Column, Delete Column


GET http://localhost:3000/api/schema
### GET all rows in the tablemeta table