GET http://localhost:3000/api/schema
### Grabs all table schemas

POST http://localhost:3000/api/schema
content-type: application/json

{
  "name": "Animals",
  "columns": [{"name":"species","type":"text"}]
}
### Adds a table