GET http://localhost:3000/api/schema
###

POST http://localhost:3000/api/schema
content-type : application/json

{
  "name" : "Penguins",
  "columns" : [
    {"name":"size","type":"text"},
  ]
}
### Adds a table

POST http://localhost:3000/api/schema
content-type : application/json

{
  "name" : "Penguins",
  "columns" : [{"name":"species","type":"text"},{"name":"age","type":"text"}]
}

### Adds a table
PUT http://localhost:3000/api/schema/f582c24a-3ead-411e-b87e-baa50e8722a4
content-type : application/json

{
  "id": "f582c24a-3ead-411e-b87e-baa50e8722a4",
  "name": "Penguins",
  "columns": [
    {
      "id": "fc54c2d6-f5c9-4568-8676-0212381565d8",
      "name": "size",
      "type": "text",
      "options": {
        "maxLength": 10,
        "minLength": 5
      }
    },
    {
      "id": "1a81443b-cc38-4d1c-bd9b-90a8e5c89fcf",
      "name": "age",
      "type": "number",
      "options": {
        "min": -5,
        "max": 5
      }
    },
    {
      "id": "1e005e42-a300-4fff-9e5e-15914613d993",
      "name": "ElephantSealBrothers",
      "type": "relation",
      "options": {
        "tableId": "f197102a-2d7b-4c30-bcba-6c62108e9977"
      }
    }
  ],
  "getAllRule": "public",
  "getOneRule": "public",
  "createRule": "public",
  "deleteRule": "public",
  "updateRule": "public"
}

### Update Column

PUT http://localhost:3000/api/schema/7464f1e2-2da9-42fa-8644-854fa179ffbb
content-type : application/json

{
  "id": "7464f1e2-2da9-42fa-8644-854fa179ffbb",
  "name": "NewOctopus",
  "columns": [
    {
      "id": "fdc30fc7-10fd-48e0-abdc-fd6562f63ec1",
      "name": "size",
      "type": "text",
      "options": {
        "minLength": 0,
        "maxLength": 255
      }
    }
  ],
  "getAllRule": "public",
  "getOneRule": "public",
  "createRule": "public",
  "deleteRule": "public",
  "updateRule": "public"
}
### Rename Table

PUT http://localhost:3000/api/schema/b14f8abd-fc0e-4eb0-97bd-c57e65690c00
content-type : application/json

{
  "id": "b14f8abd-fc0e-4eb0-97bd-c57e65690c00",
  "name" : "ElephantSeals",
  "columns" : [{"id":"fd3fb92d-0e9b-4f55-8633-42a74d0ee228", "name":"size","type":"text"}]
}
### Drop a column

PUT http://localhost:3000/api/schema/f8ef4e7f-6596-4d2f-a488-9a3c092f58cb
content-type : application/json

{
  "id": "f8ef4e7f-6596-4d2f-a488-9a3c092f58cb",
  "name" : "ElephantSeals",
  "columns" : [{"id":"b64ab088-911b-4461-836b-4747aedf5988", "name":"size","type":"text"}, {"name":"gender","type":"text"}]
}
### Add a column


PUT http://localhost:3000/api/schema/b6d31866-5668-4a92-82e3-a4dc0df24df9
content-type : application/json

{
  "id": "b6d31866-5668-4a92-82e3-a4dc0df24df9",
  "name" : "ElephantSeals",
  "columns" : [{"id":"cd5b4013-e0d3-4274-a452-ccd621c76bc9", "name":"size","type":"number"}, {"id":"720f534b-423d-4982-a894-8be36d53dce9","name":"sex","type":"text"}]
}
### Rename a column


PUT http://localhost:3000/api/schema/b14f8abd-fc0e-4eb0-97bd-c57e65690c00
content-type : application/json

{
  "id": "b14f8abd-fc0e-4eb0-97bd-c57e65690c00",
  "name" : "ArcticSeals",
  "columns" : [{"id":"fd3fb92d-0e9b-4f55-8633-42a74d0ee228", "name":"Bigness","type":"text"}, {"name":"favFood","type":"text"}]
}
### Rename table, rename column, add Column, Delete Column


### Drop Table
DELETE http://localhost:3000/api/schema/8657b606-1666-4dcb-b8c1-a9e6077283b3


### SCHEMA MIGRATION VALIDATION TESTING

### GET all rows in the tablemeta table
GET http://localhost:3000/api/schema

### Create Table
POST http://localhost:3000/api/schema
content-type : application/json

{
  "name": "bear",
  "columns": [{"name":"size", "type":"text"}]
}

### XSS Attack in Column Name Change
PUT http://localhost:3000/api/schema/36aa7616-a815-472a-8f79-148eef5b4ef1
content-type : application/json

  {
    "id": "36aa7616-a815-472a-8f79-148eef5b4ef1",
    "name": "Octopus",
    "columns": [
      {
        "id": "6a6ee214-daea-4ebc-847c-05d070064324",
        "name": "<script>alert('XSS attack')</script>",
        "type": "text",
        "options": {
          "minLength": 0,
          "maxLength": 255
        }
      }
    ],
    "getAllRule": "public",
    "getOneRule": "public",
    "createRule": "public",
    "deleteRule": "public",
    "updateRule": "public"
  }

### XSS Attack in Column Name Change
PUT http://localhost:3000/api/schema/09a4f944-5794-430e-b556-eda88d9c681a
content-type : application/json

{
  "table": {
    "id": "09a4f944-5794-430e-b556-eda88d9c681a",
    "name": "bear",
    "columns": [
      {
        "id": "b7ddc513-b912-4b3b-a0f6-8ea9901036a8",
        "name": "Bigness",
        "type": "text",
        "options": {
          "minLength": 0,
          "maxLength": 255
        }
      }
    ],
    "getAllRule": "public",
    "getOneRule": "public",
    "createRule": "public",
    "deleteRule": "public",
    "updateRule": "public"
  }
}
### Should fail